name: fund_relationship
channels:
  - conda-forge
  - defaults
dependencies:

  - python=3.9
  - numpy
  - pip
  - plotly
  - sqlalchemy>=2.0.0
  - pandas>=2.2.0
  - streamlit>=1.32.0
  - python-dotenv>=1.0.0
  # Development tools
  - black  # Code formatting
  - pylint  # Code linting
  - pytest  # Testing
  - pip:
    - pyodbc>=5.0.1  # SQL Server driver 